/*
 * Copyright (c) 2026.
 * SPDX-License-Identifier: MIT
 */
package me.bechberger.hprof.views;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;

/**
 * Assembles the full Markdown report from a built HeapGraph.
 */
public final class MarkdownWriter {

    private final HeapGraph graph;
    private final double thresholdPct;

    public MarkdownWriter(HeapGraph graph, double thresholdPct) {
        this.graph = graph;
        this.thresholdPct = thresholdPct;
    }

    public MarkdownWriter(HeapGraph graph) {
        this(graph, LeakSuspectsReport.THRESHOLD_PCT);
    }

    public void writeTo(Path outputPath) throws IOException {
        try (PrintWriter out = new PrintWriter(Files.newBufferedWriter(outputPath))) {
            write(out);
        }
    }

    void write(PrintWriter out) {
        out.printf("# Heap Dump Analysis: `%s`%n%n",
                graph.sourcePath.getFileName());
        out.printf("*Generated by hprof-redact views — %s*%n%n",
                Instant.now().toString());
        out.printf("----%n%n");

        new SystemOverviewReport(graph).write(out);
        new LeakSuspectsReport(graph, thresholdPct).write(out);
        new TopConsumersReport(graph).write(out);
    }
}
